ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_NLO-UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'R2GC_120_21 = ', R2GC_120_21
      WRITE(*,2) 'R2GC_155_37 = ', R2GC_155_37
      WRITE(*,2) 'R2GC_155_38 = ', R2GC_155_38
      WRITE(*,2) 'R2GC_156_39 = ', R2GC_156_39
      WRITE(*,2) 'R2GC_87_60 = ', R2GC_87_60
      WRITE(*,2) 'R2GC_87_61 = ', R2GC_87_61
      WRITE(*,2) 'UVGC_120_21_1eps = ', UVGC_120_21_1EPS
      WRITE(*,2) 'UVGC_123_24_1eps = ', UVGC_123_24_1EPS
      WRITE(*,2) 'UVGC_123_25_1eps = ', UVGC_123_25_1EPS
      WRITE(*,2) 'UVGC_123_26_1eps = ', UVGC_123_26_1EPS
      WRITE(*,2) 'UVGC_123_27_1eps = ', UVGC_123_27_1EPS
      WRITE(*,2) 'UVGC_123_28_1eps = ', UVGC_123_28_1EPS
      WRITE(*,2) 'UVGC_123_29_1eps = ', UVGC_123_29_1EPS
      WRITE(*,2) 'UVGC_155_54_1eps = ', UVGC_155_54_1EPS
      WRITE(*,2) 'UVGC_155_55_1eps = ', UVGC_155_55_1EPS
      WRITE(*,2) 'UVGC_156_56_1eps = ', UVGC_156_56_1EPS
      WRITE(*,2) 'UVGC_156_57_1eps = ', UVGC_156_57_1EPS
      WRITE(*,2) 'UVGC_156_58_1eps = ', UVGC_156_58_1EPS
      WRITE(*,2) 'UVGC_156_59_1eps = ', UVGC_156_59_1EPS
      WRITE(*,2) 'UVGC_171_101_1eps = ', UVGC_171_101_1EPS
      WRITE(*,2) 'UVGC_155_54 = ', UVGC_155_54
      WRITE(*,2) 'UVGC_155_55 = ', UVGC_155_55
      WRITE(*,2) 'UVGC_156_56 = ', UVGC_156_56
      WRITE(*,2) 'UVGC_156_59 = ', UVGC_156_59
      WRITE(*,2) 'UVGC_171_101 = ', UVGC_171_101
