C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjP(2,1)
C     
      SUBROUTINE FFS3L3_2(P3, F1, COUP, M2, W2, P2, COEFF)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*16 COUP
      COMPLEX*16 P3(0:3)
      COMPLEX*16 P2(0:3)
      REAL*8 W2
      COMPLEX*16 F1(*)
      REAL*8 M2
      P2(0) = +F1(1)+P3(0)
      P2(1) = +F1(2)+P3(1)
      P2(2) = +F1(3)+P3(2)
      P2(3) = +F1(4)+P3(3)
      COEFF(1,0,1)= COUP*(F1(7)*(-CI*(P2(0))+CI*(P2(3)))+F1(8)*(+CI
     $ *(P2(1))+P2(2)))
      COEFF(2,0,1)= COUP*(-1D0)*(F1(7)*(-CI*(P2(1))+P2(2))+F1(8)*(+CI
     $ *(P2(0)+P2(3))))
      COEFF(3,0,1)= COUP*CI * F1(7)*M2
      COEFF(4,0,1)= COUP*CI * F1(8)*M2
      COEFF(1,1,1)= COUP*-CI * F1(7)
      COEFF(2,1,1)= COUP*-CI * F1(8)
      COEFF(3,1,1)= 0D0
      COEFF(4,1,1)= 0D0
      COEFF(1,2,1)= COUP*CI * F1(8)
      COEFF(2,2,1)= COUP*CI * F1(7)
      COEFF(3,2,1)= 0D0
      COEFF(4,2,1)= 0D0
      COEFF(1,3,1)= COUP*F1(8)
      COEFF(2,3,1)= COUP*-F1(7)
      COEFF(3,3,1)= 0D0
      COEFF(4,3,1)= 0D0
      COEFF(1,4,1)= COUP*CI * F1(7)
      COEFF(2,4,1)= COUP*-CI * F1(8)
      COEFF(3,4,1)= 0D0
      COEFF(4,4,1)= 0D0
      END


