C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE FFV3_0(F1, F2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP10
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      TMP10 = (F1(7)*(F2(5)*(V3(5)-V3(8))-F2(6)*(V3(6)+CI*(V3(7))))
     $ +F1(8)*(F2(5)*(-V3(6)+CI*(V3(7)))+F2(6)*(V3(5)+V3(8))))
      VERTEX = COUP*(-CI * TMP10)
      END


