C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)
C     
      SUBROUTINE MP_FFS1L1_3(P1, F2, COUP, M3, W3, P3, COEFF)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      INCLUDE 'coef_specs.inc'
      COMPLEX*32 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*32 COUP
      COMPLEX*32 P3(0:3)
      COMPLEX*32 F2(*)
      COMPLEX*32 P1(0:3)
      REAL*16 W3
      REAL*16 M3
      P3(0) = +P1(0)+F2(1)
      P3(1) = +P1(1)+F2(2)
      P3(2) = +P1(2)+F2(3)
      P3(3) = +P1(3)+F2(4)
      COEFF(1,0,1)= COUP*CI * F2(5)
      COEFF(1,0,2)= COUP*CI * F2(6)
      COEFF(1,0,3)= 0Q0
      COEFF(1,0,4)= 0Q0
      END


