ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of UV_BSM_ToyModel_NLO-UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'R2GC_106_1 = ', R2GC_106_1
      WRITE(*,2) 'R2GC_108_3 = ', R2GC_108_3
      WRITE(*,2) 'R2GC_108_4 = ', R2GC_108_4
      WRITE(*,2) 'R2GC_108_5 = ', R2GC_108_5
      WRITE(*,2) 'R2GC_136_21 = ', R2GC_136_21
      WRITE(*,2) 'R2GC_136_22 = ', R2GC_136_22
      WRITE(*,2) 'R2GC_137_23 = ', R2GC_137_23
      WRITE(*,2) 'R2GC_159_36 = ', R2GC_159_36
      WRITE(*,2) 'UVGC_111_2_1eps = ', UVGC_111_2_1EPS
      WRITE(*,2) 'UVGC_136_23_1eps = ', UVGC_136_23_1EPS
      WRITE(*,2) 'UVGC_136_24_1eps = ', UVGC_136_24_1EPS
      WRITE(*,2) 'UVGC_136_25_1eps = ', UVGC_136_25_1EPS
      WRITE(*,2) 'UVGC_137_26_1eps = ', UVGC_137_26_1EPS
      WRITE(*,2) 'UVGC_137_27_1eps = ', UVGC_137_27_1EPS
      WRITE(*,2) 'UVGC_137_28_1eps = ', UVGC_137_28_1EPS
      WRITE(*,2) 'UVGC_137_29_1eps = ', UVGC_137_29_1EPS
      WRITE(*,2) 'UVGC_137_30_1eps = ', UVGC_137_30_1EPS
      WRITE(*,2) 'UVGC_141_41_1eps = ', UVGC_141_41_1EPS
      WRITE(*,2) 'UVGC_141_42_1eps = ', UVGC_141_42_1EPS
      WRITE(*,2) 'UVGC_141_43_1eps = ', UVGC_141_43_1EPS
      WRITE(*,2) 'UVGC_141_46_1eps = ', UVGC_141_46_1EPS
      WRITE(*,2) 'UVGC_156_86_1eps = ', UVGC_156_86_1EPS
      WRITE(*,2) 'UVGC_159_91_1eps = ', UVGC_159_91_1EPS
      WRITE(*,2) 'UVGC_136_23 = ', UVGC_136_23
      WRITE(*,2) 'UVGC_136_24 = ', UVGC_136_24
      WRITE(*,2) 'UVGC_136_25 = ', UVGC_136_25
      WRITE(*,2) 'UVGC_137_26 = ', UVGC_137_26
      WRITE(*,2) 'UVGC_137_29 = ', UVGC_137_29
      WRITE(*,2) 'UVGC_137_30 = ', UVGC_137_30
      WRITE(*,2) 'UVGC_141_40 = ', UVGC_141_40
      WRITE(*,2) 'UVGC_141_44 = ', UVGC_141_44
      WRITE(*,2) 'UVGC_141_45 = ', UVGC_141_45
      WRITE(*,2) 'UVGC_156_86 = ', UVGC_156_86
      WRITE(*,2) 'UVGC_156_87 = ', UVGC_156_87
      WRITE(*,2) 'UVGC_159_91 = ', UVGC_159_91
      WRITE(*,2) 'GC_89 = ', GC_89
