ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Top-EFTfull-UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_88 = ', GC_88
      WRITE(*,2) 'GC_92 = ', GC_92
