C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(-1,1)*Gamma(-1,2,-2)*ProjM(-2,1)) + Coup(2) * (P(-1,1)*Gamma(-1,2,-2)*ProjP(-2,1)) + Coup(3) * (ProjM(2,1) + ProjP(2,1))
C     
      SUBROUTINE FF3_5_6_0(F1, F2, COUP1, COUP2, COUP3,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 P1(0:3)
      COMPLEX*16 TMP17
      COMPLEX*16 TMP18
      COMPLEX*16 TMP23
      COMPLEX*16 TMP24
      COMPLEX*16 VERTEX
      P1(0) = F1(1)
      P1(1) = F1(2)
      P1(2) = F1(3)
      P1(3) = F1(4)
      TMP17 = (F1(5)*F2(5)+F1(6)*F2(6))
      TMP18 = (F1(7)*F2(7)+F1(8)*F2(8))
      TMP23 = (F1(5)*(F2(7)*(P1(0)+P1(3))+F2(8)*(P1(1)+CI*(P1(2))))
     $ +F1(6)*(F2(7)*(P1(1)-CI*(P1(2)))+F2(8)*(P1(0)-P1(3))))
      TMP24 = (F1(7)*(F2(5)*(P1(0)-P1(3))-F2(6)*(P1(1)+CI*(P1(2))))
     $ +F1(8)*(F2(5)*(-P1(1)+CI*(P1(2)))+F2(6)*(P1(0)+P1(3))))
      VERTEX = (-1D0)*(COUP3*(+CI*(TMP17+TMP18))+(+CI*(TMP23*COUP1
     $ +TMP24*COUP2)))
      END


