C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(1,2)*P(2,2)) + Coup(2) * (P(-1,2)**2*Metric(1,2))
C     
      SUBROUTINE VV1_3_0(V1, V2, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 P2(0:3)
      COMPLEX*16 TMP13
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP9
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 VERTEX
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      TMP13 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP5 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      TMP6 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP9 = (P2(0)*V2(5)-P2(1)*V2(6)-P2(2)*V2(7)-P2(3)*V2(8))
      VERTEX = (-1D0)*(+CI*(TMP9*TMP13*COUP1+TMP5*TMP6*COUP2))
      END


