C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(3,1)*Metric(1,2) + P(2,3)*Metric(1,3) + P(1,2)*Metric(2,3)) + Coup(2) * (P(3,2)*Metric(1,2) + P(2,1)*Metric(1,3) + P(1,3)*Metric(2,3))
C     
      SUBROUTINE VVV10_11L2P0_1(P2, V3, COUP1, COUP2, M1, W1, P1,
     $  COEFF)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 V3(*)
      COMPLEX*16 P2(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 COUP1
      COMPLEX*16 P3(0:3)
      COMPLEX*16 TMP1
      REAL*8 M1
      REAL*8 W1
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*16 P1(0:3)
      P3(0) = V3(1)
      P3(1) = V3(2)
      P3(2) = V3(3)
      P3(3) = V3(4)
      P1(0) = +P2(0)+V3(1)
      P1(1) = +P2(1)+V3(2)
      P1(2) = +P2(2)+V3(3)
      P1(3) = +P2(3)+V3(4)
      TMP1 = (P2(0)*V3(5)-P2(1)*V3(6)-P2(2)*V3(7)-P2(3)*V3(8))
      TMP0 = (V3(5)*P1(0)-V3(6)*P1(1)-V3(7)*P1(2)-V3(8)*P1(3))
      COEFF(1,0,1)= (-1D0)*(V3(5)*(COUP1*(+CI*(P3(0)+P2(0)))+COUP2*(
     $ -CI*(P1(0))+CI*(P3(0))))+(-CI*(TMP0*COUP1)+CI*(TMP1*COUP2)))
      COEFF(2,0,1)= (-1D0)*(COUP1*(+CI*(V3(6)*P3(0)+P2(1)*V3(5)))
     $ +COUP2*(-CI*(V3(6)*P1(0))+CI*(V3(5)*P3(1))))
      COEFF(3,0,1)= (-1D0)*(COUP1*(+CI*(V3(7)*P3(0)+P2(2)*V3(5)))
     $ +COUP2*(-CI*(V3(7)*P1(0))+CI*(V3(5)*P3(2))))
      COEFF(4,0,1)= (-1D0)*(COUP1*(+CI*(V3(8)*P3(0)+P2(3)*V3(5)))
     $ +COUP2*(-CI*(V3(8)*P1(0))+CI*(V3(5)*P3(3))))
      COEFF(1,1,1)= 0D0
      COEFF(2,1,1)= CI * V3(6)*COUP2
      COEFF(3,1,1)= CI * V3(7)*COUP2
      COEFF(4,1,1)= CI * V3(8)*COUP2
      COEFF(1,2,1)= V3(6)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(2,2,1)= -CI * V3(5)*COUP1
      COEFF(3,2,1)= 0D0
      COEFF(4,2,1)= 0D0
      COEFF(1,3,1)= V3(7)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(2,3,1)= 0D0
      COEFF(3,3,1)= -CI * V3(5)*COUP1
      COEFF(4,3,1)= 0D0
      COEFF(1,4,1)= V3(8)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(2,4,1)= 0D0
      COEFF(3,4,1)= 0D0
      COEFF(4,4,1)= -CI * V3(5)*COUP1
      COEFF(1,0,2)= (COUP1*(+CI*(V3(5)*P3(1)+P2(0)*V3(6)))+COUP2*(-CI
     $ *(V3(5)*P1(1))+CI*(V3(6)*P3(0))))
      COEFF(2,0,2)= (V3(6)*(COUP1*(+CI*(P3(1)+P2(1)))+COUP2*(-CI*(P1(1)
     $ )+CI*(P3(1))))+(+CI*(TMP0*COUP1)-CI*(TMP1*COUP2)))
      COEFF(3,0,2)= (COUP1*(+CI*(V3(7)*P3(1)+P2(2)*V3(6)))+COUP2*(-CI
     $ *(V3(7)*P1(1))+CI*(V3(6)*P3(2))))
      COEFF(4,0,2)= (COUP1*(+CI*(V3(8)*P3(1)+P2(3)*V3(6)))+COUP2*(-CI
     $ *(V3(8)*P1(1))+CI*(V3(6)*P3(3))))
      COEFF(1,1,2)= CI * V3(6)*COUP1
      COEFF(2,1,2)= V3(5)*(+CI*(COUP1)-CI*(COUP2))
      COEFF(3,1,2)= 0D0
      COEFF(4,1,2)= 0D0
      COEFF(1,2,2)= -CI * V3(5)*COUP2
      COEFF(2,2,2)= 0D0
      COEFF(3,2,2)= -CI * V3(7)*COUP2
      COEFF(4,2,2)= -CI * V3(8)*COUP2
      COEFF(1,3,2)= 0D0
      COEFF(2,3,2)= V3(7)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(3,3,2)= CI * V3(6)*COUP1
      COEFF(4,3,2)= 0D0
      COEFF(1,4,2)= 0D0
      COEFF(2,4,2)= V3(8)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(3,4,2)= 0D0
      COEFF(4,4,2)= CI * V3(6)*COUP1
      COEFF(1,0,3)= (COUP1*(+CI*(V3(5)*P3(2)+P2(0)*V3(7)))+COUP2*(-CI
     $ *(V3(5)*P1(2))+CI*(V3(7)*P3(0))))
      COEFF(2,0,3)= (COUP1*(+CI*(V3(6)*P3(2)+P2(1)*V3(7)))+COUP2*(-CI
     $ *(V3(6)*P1(2))+CI*(V3(7)*P3(1))))
      COEFF(3,0,3)= (V3(7)*(COUP1*(+CI*(P3(2)+P2(2)))+COUP2*(-CI*(P1(2)
     $ )+CI*(P3(2))))+(+CI*(TMP0*COUP1)-CI*(TMP1*COUP2)))
      COEFF(4,0,3)= (COUP1*(+CI*(V3(8)*P3(2)+P2(3)*V3(7)))+COUP2*(-CI
     $ *(V3(8)*P1(2))+CI*(V3(7)*P3(3))))
      COEFF(1,1,3)= CI * V3(7)*COUP1
      COEFF(2,1,3)= 0D0
      COEFF(3,1,3)= V3(5)*(+CI*(COUP1)-CI*(COUP2))
      COEFF(4,1,3)= 0D0
      COEFF(1,2,3)= 0D0
      COEFF(2,2,3)= CI * V3(7)*COUP1
      COEFF(3,2,3)= V3(6)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(4,2,3)= 0D0
      COEFF(1,3,3)= -CI * V3(5)*COUP2
      COEFF(2,3,3)= -CI * V3(6)*COUP2
      COEFF(3,3,3)= 0D0
      COEFF(4,3,3)= -CI * V3(8)*COUP2
      COEFF(1,4,3)= 0D0
      COEFF(2,4,3)= 0D0
      COEFF(3,4,3)= V3(8)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(4,4,3)= CI * V3(7)*COUP1
      COEFF(1,0,4)= (COUP1*(+CI*(V3(5)*P3(3)+P2(0)*V3(8)))+COUP2*(-CI
     $ *(V3(5)*P1(3))+CI*(V3(8)*P3(0))))
      COEFF(2,0,4)= (COUP1*(+CI*(V3(6)*P3(3)+P2(1)*V3(8)))+COUP2*(-CI
     $ *(V3(6)*P1(3))+CI*(V3(8)*P3(1))))
      COEFF(3,0,4)= (COUP1*(+CI*(V3(7)*P3(3)+P2(2)*V3(8)))+COUP2*(-CI
     $ *(V3(7)*P1(3))+CI*(V3(8)*P3(2))))
      COEFF(4,0,4)= (V3(8)*(COUP1*(+CI*(P3(3)+P2(3)))+COUP2*(-CI*(P1(3)
     $ )+CI*(P3(3))))+(+CI*(TMP0*COUP1)-CI*(TMP1*COUP2)))
      COEFF(1,1,4)= CI * V3(8)*COUP1
      COEFF(2,1,4)= 0D0
      COEFF(3,1,4)= 0D0
      COEFF(4,1,4)= V3(5)*(+CI*(COUP1)-CI*(COUP2))
      COEFF(1,2,4)= 0D0
      COEFF(2,2,4)= CI * V3(8)*COUP1
      COEFF(3,2,4)= 0D0
      COEFF(4,2,4)= V3(6)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(1,3,4)= 0D0
      COEFF(2,3,4)= 0D0
      COEFF(3,3,4)= CI * V3(8)*COUP1
      COEFF(4,3,4)= V3(7)*(-CI*(COUP1)+CI*(COUP2))
      COEFF(1,4,4)= -CI * V3(5)*COUP2
      COEFF(2,4,4)= -CI * V3(6)*COUP2
      COEFF(3,4,4)= -CI * V3(7)*COUP2
      COEFF(4,4,4)= 0D0
      END


