C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,3)*Metric(2,4)
C     
      SUBROUTINE VVVV2P0_1(V2, V3, V4, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M1
      COMPLEX*16 P1(0:3)
      COMPLEX*16 TMP4
      COMPLEX*16 V1(8)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 V4(*)
      REAL*8 W1
      COMPLEX*16 DENOM
      V1(1) = +V2(1)+V3(1)+V4(1)
      V1(2) = +V2(2)+V3(2)+V4(2)
      V1(3) = +V2(3)+V3(3)+V4(3)
      V1(4) = +V2(4)+V3(4)+V4(4)
      P1(0) = -V1(1)
      P1(1) = -V1(2)
      P1(2) = -V1(3)
      P1(3) = -V1(4)
      TMP4 = (V2(5)*V4(5)-V2(6)*V4(6)-V2(7)*V4(7)-V2(8)*V4(8))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(5)= DENOM*(-CI )* TMP4*V3(5)
      V1(6)= DENOM*(-CI )* TMP4*V3(6)
      V1(7)= DENOM*(-CI )* TMP4*V3(7)
      V1(8)= DENOM*(-CI )* TMP4*V3(8)
      END


