C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Metric(1,4)*Metric(2,3)) + Coup(2) * (Metric(1,3)*Metric(2,4))
C     
      SUBROUTINE VVVV1_2L2P0_1(P2, V3, V4, COUP1, COUP2, M1, W1, P1,
     $  COEFF)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP2
      COMPLEX*16 V3(*)
      COMPLEX*16 P2(0:3)
      REAL*8 M1
      COMPLEX*16 COUP1
      REAL*8 W1
      COMPLEX*16 V4(*)
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*16 P1(0:3)
      P1(0) = +P2(0)+V3(1)+V4(1)
      P1(1) = +P2(1)+V3(2)+V4(2)
      P1(2) = +P2(2)+V3(3)+V4(3)
      P1(3) = +P2(3)+V3(4)+V4(4)
      COEFF(1,0,1)= -V3(5)*V4(5)*(+CI*(COUP1+COUP2))
      COEFF(2,0,1)= (-1D0)*(+CI*(V3(5)*V4(6)*COUP1+V3(6)*V4(5)*COUP2))
      COEFF(3,0,1)= (-1D0)*(+CI*(V3(5)*V4(7)*COUP1+V3(7)*V4(5)*COUP2))
      COEFF(4,0,1)= (-1D0)*(+CI*(V3(5)*V4(8)*COUP1+V3(8)*V4(5)*COUP2))
      COEFF(1,0,2)= (+CI*(V3(6)*V4(5)*COUP1+V3(5)*V4(6)*COUP2))
      COEFF(2,0,2)= V3(6)*V4(6)*(+CI*(COUP1+COUP2))
      COEFF(3,0,2)= (+CI*(V3(6)*V4(7)*COUP1+V3(7)*V4(6)*COUP2))
      COEFF(4,0,2)= (+CI*(V3(6)*V4(8)*COUP1+V3(8)*V4(6)*COUP2))
      COEFF(1,0,3)= (+CI*(V3(7)*V4(5)*COUP1+V3(5)*V4(7)*COUP2))
      COEFF(2,0,3)= (+CI*(V3(7)*V4(6)*COUP1+V3(6)*V4(7)*COUP2))
      COEFF(3,0,3)= V3(7)*V4(7)*(+CI*(COUP1+COUP2))
      COEFF(4,0,3)= (+CI*(V3(7)*V4(8)*COUP1+V3(8)*V4(7)*COUP2))
      COEFF(1,0,4)= (+CI*(V3(8)*V4(5)*COUP1+V3(5)*V4(8)*COUP2))
      COEFF(2,0,4)= (+CI*(V3(8)*V4(6)*COUP1+V3(6)*V4(8)*COUP2))
      COEFF(3,0,4)= (+CI*(V3(8)*V4(7)*COUP1+V3(7)*V4(8)*COUP2))
      COEFF(4,0,4)= V3(8)*V4(8)*(+CI*(COUP1+COUP2))
      END


