C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Gamma(3,2,1)) + Coup(2) * (Gamma(3,2,-1)*ProjM(-1,1) + Gamma(3,2,-1)*ProjP(-1,1))
C     
      SUBROUTINE MP_FFV1_7L2P0_3(P2, F1, COUP1, COUP2, M3, W3, P3,
     $  COEFF)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 F1(*)
      COMPLEX*32 P2(0:3)
      COMPLEX*32 COUP1
      COMPLEX*32 P3(0:3)
      INCLUDE 'coef_specs.inc'
      COMPLEX*32 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      REAL*16 W3
      COMPLEX*32 COUP2
      REAL*16 M3
      P3(0) = +F1(1)+P2(0)
      P3(1) = +F1(2)+P2(1)
      P3(2) = +F1(3)+P2(2)
      P3(3) = +F1(4)+P2(3)
      COEFF(1,0,1)= -F1(7)*(+CI*(COUP2+COUP1))
      COEFF(2,0,1)= -F1(8)*(+CI*(COUP2+COUP1))
      COEFF(3,0,1)= -F1(8)*(COUP2+COUP1)
      COEFF(4,0,1)= -F1(7)*(+CI*(COUP2+COUP1))
      COEFF(1,0,2)= -F1(8)*(+CI*(COUP2+COUP1))
      COEFF(2,0,2)= -F1(7)*(+CI*(COUP2+COUP1))
      COEFF(3,0,2)= F1(7)*(COUP2+COUP1)
      COEFF(4,0,2)= F1(8)*(+CI*(COUP2+COUP1))
      COEFF(1,0,3)= -F1(5)*(+CI*(COUP2+COUP1))
      COEFF(2,0,3)= F1(6)*(+CI*(COUP2+COUP1))
      COEFF(3,0,3)= F1(6)*(COUP2+COUP1)
      COEFF(4,0,3)= F1(5)*(+CI*(COUP2+COUP1))
      COEFF(1,0,4)= -F1(6)*(+CI*(COUP2+COUP1))
      COEFF(2,0,4)= F1(5)*(+CI*(COUP2+COUP1))
      COEFF(3,0,4)= -F1(5)*(COUP2+COUP1)
      COEFF(4,0,4)= -F1(6)*(+CI*(COUP2+COUP1))
      END


