(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"DMsimp_s_spin1",
  Authors -> {"A. Martini, K. Mawatari, J. Wang, C. Zhang, B. Zaldivar, B. Fuks"},
  Institutions -> {"Universite catholique de Louvain, LPSC Grenoble, Johnnas Gutenberg University of Mainz, Brookhaven National Laboratory, LAPTh Annecy, LPTHE / UPMC"},
  Emails -> {"kentarou.mawatari@lpsc.in2p3.fr", "cenzhang@bnl.gov"},
  URLs -> "http://feynrules.irmp.ucl.ac.be/wiki/DMsimp/",
  References -> {"O. Mattelaer et al., arXiv:1508.00564", "M. Backovic et al., arXiv:1508.05327", "M. Neubert et al., arXiv:1509.05785", "J. Andrea et al., arXiv:1106.6199"},
  Version -> "2.1",
  Date -> "2016.10.27"};

FR$ClassesTranslation={G -> V[1], ghG -> U[1], u -> F[1], c -> F[2], t -> F[3], d -> F[4], s -> F[5], b -> F[6], Y1 -> V[2]};

FR$InteractionOrderPerturbativeExpansion={{DMV, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MY1,
    Indices -> {},
    PropagatorLabel -> "Y1" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[G];
GaugeXi[ V[2] ] = GaugeXi[V[7]];

MT[ ___ ] := MT;
MB[ ___ ] := MB;
MY1[ ___ ] := MY1;


TheLabel[ V[1, {__}] ] := TheLabel[V[1]];
TheLabel[ U[1, {__}] ] := TheLabel[U[1]];
TheLabel[ F[1, {__}] ] := TheLabel[F[1]];
TheLabel[ F[2, {__}] ] := TheLabel[F[2]];
TheLabel[ F[3, {__}] ] := TheLabel[F[3]];
TheLabel[ F[4, {__}] ] := TheLabel[F[4]];
TheLabel[ F[5, {__}] ] := TheLabel[F[5]];
TheLabel[ F[6, {__}] ] := TheLabel[F[6]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[1, {e1x2}] , V[1, {e2x2}] ] == {{0, I*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, (-I)*FR$deltaZ[{G, G}, {{}}]*IndexDelta[e1x2, e2x2]}},

C[ V[2] , V[2] ] == {{0, I*FR$deltaZ[{Y1, Y1}, {{}}]}, {0, I*MY1*(2*FR$delta[{MY1}, {}] + MY1*FR$deltaZ[{Y1, Y1}, {{}}])}, {0, (-I)*FR$deltaZ[{Y1, Y1}, {{}}]}},

C[ -F[3, {e1x2}] , F[3, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{t, t}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{t, t}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*(2*FR$delta[{MT}, {}] + MT*FR$deltaZ[{t, t}, {{}}, "L"] + MT*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -U[1, {e1x1}] , U[1, {e2x1}] , V[1, {e3x2}] ] == {{gc4*SUNF[e3x2, e1x1, e2x1], -1/2*(GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e3x2, e1x1, e2x1])/aS}, {0, 0}},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] ] == {{-(GS*SUNF[e1x2, e2x2, e3x2]), -1/2*(GS*(FR$delta[{aS}, {}] + 3*aS*FR$deltaZ[{G, G}, {{}}])*SUNF[e1x2, e2x2, e3x2])/aS}},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] , V[1, {e4x2}] ] == {{(-I)*gc6*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {(-I)*gc6*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), ((-I)*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]))/aS}, {I*gc6*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), (I*GS^2*(FR$delta[{aS}, {}] + 2*aS*FR$deltaZ[{G, G}, {{}}])*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]))/aS}},

C[ -F[6, {e1x2}] , F[6, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{b, b}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{b, b}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2}] , F[4, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{d, d}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{d, d}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[5, {e1x2}] , F[5, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{s, s}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{s, s}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{c, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{c, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] ] == {{0, (-I)*FR$deltaZ[{u, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, I*FR$deltaZ[{u, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[3, {e1x2}] , F[2, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + FR$deltaZ[{t, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*FR$deltaZ[{t, c}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*FR$deltaZ[{t, c}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[3, {e1x2}] , F[1, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + FR$deltaZ[{t, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*FR$deltaZ[{t, u}, {{}}, "L"]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*FR$deltaZ[{t, u}, {{}}, "R"]*IndexDelta[e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[3, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + FR$deltaZ[{c, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]]*IndexDelta[e1x2, e2x2]}},

C[ -F[1, {e1x2}] , F[3, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + FR$deltaZ[{u, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]]*IndexDelta[e1x2, e2x2]}, {0, (-1/2*I)*MT*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]]*IndexDelta[e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1, {e3x2}] ] == {{I*gc16*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc16*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{c, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[3, {e1x2}] , F[3, {e2x2}] , V[1, {e3x2}] ] == {{I*gc17*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc17*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{t, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[1, {e3x2}] ] == {{I*gc18*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc18*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{u, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[6, {e1x2}] , F[6, {e2x2}] , V[1, {e3x2}] ] == {{I*gc19*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc19*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{b, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[4, {e1x2}] , F[4, {e2x2}] , V[1, {e3x2}] ] == {{I*gc20*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc20*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{d, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[5, {e1x2}] , F[5, {e2x2}] , V[1, {e3x2}] ] == {{I*gc21*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2])/aS}, {I*gc21*SUNT[e3x2, e1x2, e2x2], ((I/2)*GS*(FR$delta[{aS}, {}] + aS*FR$deltaZ[{G, G}, {{}}] + 2*aS*FR$deltaZ[{s, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2])/aS}},

C[ -F[6, {e1x2}] , F[6, {e2x2}] , V[2] ] == {{I*gc22L*IndexDelta[e1x2, e2x2], (-1/2*I)*(2*FR$delta[{gAd33}, {}] - 2*FR$delta[{gVd33}, {}] + gAd33*FR$deltaZ[{Y1, Y1}, {{}}] - gVd33*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAd33*FR$deltaZ[{b, b}, {{}}, "L"] - 2*gVd33*FR$deltaZ[{b, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {I*gc22R*IndexDelta[e1x2, e2x2], (I/2)*(2*FR$delta[{gAd33}, {}] + 2*FR$delta[{gVd33}, {}] + gAd33*FR$deltaZ[{Y1, Y1}, {{}}] + gVd33*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAd33*FR$deltaZ[{b, b}, {{}}, "R"] + 2*gVd33*FR$deltaZ[{b, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc23L*IndexDelta[e1x2, e2x2], (-1/2*I)*(2*FR$delta[{gAu22}, {}] - 2*FR$delta[{gVu22}, {}] + gAu22*FR$deltaZ[{Y1, Y1}, {{}}] - gVu22*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAu22*FR$deltaZ[{c, c}, {{}}, "L"] - 2*gVu22*FR$deltaZ[{c, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {I*gc23R*IndexDelta[e1x2, e2x2], (I/2)*(2*FR$delta[{gAu22}, {}] + 2*FR$delta[{gVu22}, {}] + gAu22*FR$deltaZ[{Y1, Y1}, {{}}] + gVu22*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAu22*FR$deltaZ[{c, c}, {{}}, "R"] + 2*gVu22*FR$deltaZ[{c, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[4, {e1x2}] , F[4, {e2x2}] , V[2] ] == {{I*gc24L*IndexDelta[e1x2, e2x2], (-1/2*I)*(2*FR$delta[{gAd11}, {}] - 2*FR$delta[{gVd11}, {}] + gAd11*FR$deltaZ[{Y1, Y1}, {{}}] - gVd11*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAd11*FR$deltaZ[{d, d}, {{}}, "L"] - 2*gVd11*FR$deltaZ[{d, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {I*gc24R*IndexDelta[e1x2, e2x2], (I/2)*(2*FR$delta[{gAd11}, {}] + 2*FR$delta[{gVd11}, {}] + gAd11*FR$deltaZ[{Y1, Y1}, {{}}] + gVd11*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAd11*FR$deltaZ[{d, d}, {{}}, "R"] + 2*gVd11*FR$deltaZ[{d, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[5, {e1x2}] , F[5, {e2x2}] , V[2] ] == {{I*gc25L*IndexDelta[e1x2, e2x2], (-1/2*I)*(2*FR$delta[{gAd22}, {}] - 2*FR$delta[{gVd22}, {}] + gAd22*FR$deltaZ[{Y1, Y1}, {{}}] - gVd22*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAd22*FR$deltaZ[{s, s}, {{}}, "L"] - 2*gVd22*FR$deltaZ[{s, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {I*gc25R*IndexDelta[e1x2, e2x2], (I/2)*(2*FR$delta[{gAd22}, {}] + 2*FR$delta[{gVd22}, {}] + gAd22*FR$deltaZ[{Y1, Y1}, {{}}] + gVd22*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAd22*FR$deltaZ[{s, s}, {{}}, "R"] + 2*gVd22*FR$deltaZ[{s, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[3, {e1x2}] , F[3, {e2x2}] , V[2] ] == {{I*gc26L*IndexDelta[e1x2, e2x2], (-1/2*I)*(2*FR$delta[{gAu33}, {}] - 2*FR$delta[{gVu33}, {}] + gAu33*FR$deltaZ[{Y1, Y1}, {{}}] - gVu33*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAu33*FR$deltaZ[{t, t}, {{}}, "L"] - 2*gVu33*FR$deltaZ[{t, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {I*gc26R*IndexDelta[e1x2, e2x2], (I/2)*(2*FR$delta[{gAu33}, {}] + 2*FR$delta[{gVu33}, {}] + gAu33*FR$deltaZ[{Y1, Y1}, {{}}] + gVu33*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAu33*FR$deltaZ[{t, t}, {{}}, "R"] + 2*gVu33*FR$deltaZ[{t, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc27L*IndexDelta[e1x2, e2x2], (-1/2*I)*(2*FR$delta[{gAu11}, {}] - 2*FR$delta[{gVu11}, {}] + gAu11*FR$deltaZ[{Y1, Y1}, {{}}] - gVu11*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAu11*FR$deltaZ[{u, u}, {{}}, "L"] - 2*gVu11*FR$deltaZ[{u, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {I*gc27R*IndexDelta[e1x2, e2x2], (I/2)*(2*FR$delta[{gAu11}, {}] + 2*FR$delta[{gVu11}, {}] + gAu11*FR$deltaZ[{Y1, Y1}, {{}}] + gVu11*FR$deltaZ[{Y1, Y1}, {{}}] + 2*gAu11*FR$deltaZ[{u, u}, {{}}, "R"] + 2*gVu11*FR$deltaZ[{u, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[6, {e1x2}] , F[4, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + FR$deltaZ[{b, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[6, {e1x2}] , F[5, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + FR$deltaZ[{b, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2}] , F[6, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + FR$deltaZ[{d, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[4, {e1x2}] , F[5, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[5, {e1x2}] , F[6, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + FR$deltaZ[{s, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[5, {e1x2}] , F[4, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] ] == {{0, (-1/2*I)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}, {0, 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[3, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + FR$deltaZ[{c, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + FR$deltaZ[{c, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + FR$deltaZ[{c, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + FR$deltaZ[{c, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[3, {e1x2}] , F[2, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + FR$deltaZ[{t, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + FR$deltaZ[{t, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[3, {e1x2}] , F[1, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + FR$deltaZ[{t, u}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + FR$deltaZ[{t, u}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + FR$deltaZ[{u, c}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + FR$deltaZ[{u, c}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[1, {e1x2}] , F[3, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + FR$deltaZ[{u, t}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + FR$deltaZ[{u, t}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[6, {e1x2}] , F[4, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + FR$deltaZ[{b, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + FR$deltaZ[{b, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[6, {e1x2}] , F[5, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + FR$deltaZ[{b, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + FR$deltaZ[{b, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[4, {e1x2}] , F[6, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + FR$deltaZ[{d, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + FR$deltaZ[{d, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[4, {e1x2}] , F[5, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + FR$deltaZ[{d, s}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + FR$deltaZ[{d, s}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[5, {e1x2}] , F[6, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + FR$deltaZ[{s, b}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + FR$deltaZ[{s, b}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[5, {e1x2}] , F[4, {e2x2}] , V[1, {e3x2}] ] == {{0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + FR$deltaZ[{s, d}, {{}}, "L"])*SUNT[e3x2, e1x2, e2x2]}, {0, (I/2)*GS*(Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + FR$deltaZ[{s, d}, {{}}, "R"])*SUNT[e3x2, e1x2, e2x2]}},

C[ -F[6, {e1x2}] , F[4, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAd11*Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] - gVd11*Conjugate[FR$deltaZ[{d, b}, {{}}, "L"]] + gAd33*FR$deltaZ[{b, d}, {{}}, "L"] - gVd33*FR$deltaZ[{b, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAd11*Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + gVd11*Conjugate[FR$deltaZ[{d, b}, {{}}, "R"]] + gAd33*FR$deltaZ[{b, d}, {{}}, "R"] + gVd33*FR$deltaZ[{b, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[6, {e1x2}] , F[5, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAd22*Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] - gVd22*Conjugate[FR$deltaZ[{s, b}, {{}}, "L"]] + gAd33*FR$deltaZ[{b, s}, {{}}, "L"] - gVd33*FR$deltaZ[{b, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAd22*Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + gVd22*Conjugate[FR$deltaZ[{s, b}, {{}}, "R"]] + gAd33*FR$deltaZ[{b, s}, {{}}, "R"] + gVd33*FR$deltaZ[{b, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[3, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAu33*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] - gVu33*Conjugate[FR$deltaZ[{t, c}, {{}}, "L"]] + gAu22*FR$deltaZ[{c, t}, {{}}, "L"] - gVu22*FR$deltaZ[{c, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAu33*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + gVu33*Conjugate[FR$deltaZ[{t, c}, {{}}, "R"]] + gAu22*FR$deltaZ[{c, t}, {{}}, "R"] + gVu22*FR$deltaZ[{c, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAu11*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] - gVu11*Conjugate[FR$deltaZ[{u, c}, {{}}, "L"]] + gAu22*FR$deltaZ[{c, u}, {{}}, "L"] - gVu22*FR$deltaZ[{c, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAu11*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + gVu11*Conjugate[FR$deltaZ[{u, c}, {{}}, "R"]] + gAu22*FR$deltaZ[{c, u}, {{}}, "R"] + gVu22*FR$deltaZ[{c, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[4, {e1x2}] , F[6, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAd33*Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] - gVd33*Conjugate[FR$deltaZ[{b, d}, {{}}, "L"]] + gAd11*FR$deltaZ[{d, b}, {{}}, "L"] - gVd11*FR$deltaZ[{d, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAd33*Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + gVd33*Conjugate[FR$deltaZ[{b, d}, {{}}, "R"]] + gAd11*FR$deltaZ[{d, b}, {{}}, "R"] + gVd11*FR$deltaZ[{d, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[4, {e1x2}] , F[5, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAd22*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] - gVd22*Conjugate[FR$deltaZ[{s, d}, {{}}, "L"]] + gAd11*FR$deltaZ[{d, s}, {{}}, "L"] - gVd11*FR$deltaZ[{d, s}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAd22*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + gVd22*Conjugate[FR$deltaZ[{s, d}, {{}}, "R"]] + gAd11*FR$deltaZ[{d, s}, {{}}, "R"] + gVd11*FR$deltaZ[{d, s}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[5, {e1x2}] , F[6, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAd33*Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] - gVd33*Conjugate[FR$deltaZ[{b, s}, {{}}, "L"]] + gAd22*FR$deltaZ[{s, b}, {{}}, "L"] - gVd22*FR$deltaZ[{s, b}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAd33*Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + gVd33*Conjugate[FR$deltaZ[{b, s}, {{}}, "R"]] + gAd22*FR$deltaZ[{s, b}, {{}}, "R"] + gVd22*FR$deltaZ[{s, b}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[5, {e1x2}] , F[4, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAd11*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] - gVd11*Conjugate[FR$deltaZ[{d, s}, {{}}, "L"]] + gAd22*FR$deltaZ[{s, d}, {{}}, "L"] - gVd22*FR$deltaZ[{s, d}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAd11*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + gVd11*Conjugate[FR$deltaZ[{d, s}, {{}}, "R"]] + gAd22*FR$deltaZ[{s, d}, {{}}, "R"] + gVd22*FR$deltaZ[{s, d}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[3, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAu22*Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] - gVu22*Conjugate[FR$deltaZ[{c, t}, {{}}, "L"]] + gAu33*FR$deltaZ[{t, c}, {{}}, "L"] - gVu33*FR$deltaZ[{t, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAu22*Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + gVu22*Conjugate[FR$deltaZ[{c, t}, {{}}, "R"]] + gAu33*FR$deltaZ[{t, c}, {{}}, "R"] + gVu33*FR$deltaZ[{t, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[3, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAu11*Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] - gVu11*Conjugate[FR$deltaZ[{u, t}, {{}}, "L"]] + gAu33*FR$deltaZ[{t, u}, {{}}, "L"] - gVu33*FR$deltaZ[{t, u}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAu11*Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + gVu11*Conjugate[FR$deltaZ[{u, t}, {{}}, "R"]] + gAu33*FR$deltaZ[{t, u}, {{}}, "R"] + gVu33*FR$deltaZ[{t, u}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAu22*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] - gVu22*Conjugate[FR$deltaZ[{c, u}, {{}}, "L"]] + gAu11*FR$deltaZ[{u, c}, {{}}, "L"] - gVu11*FR$deltaZ[{u, c}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAu22*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + gVu22*Conjugate[FR$deltaZ[{c, u}, {{}}, "R"]] + gAu11*FR$deltaZ[{u, c}, {{}}, "R"] + gVu11*FR$deltaZ[{u, c}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}},

C[ -F[1, {e1x2}] , F[3, {e2x2}] , V[2] ] == {{0, (-1/2*I)*(gAu33*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] - gVu33*Conjugate[FR$deltaZ[{t, u}, {{}}, "L"]] + gAu11*FR$deltaZ[{u, t}, {{}}, "L"] - gVu11*FR$deltaZ[{u, t}, {{}}, "L"])*IndexDelta[e1x2, e2x2]}, {0, (I/2)*(gAu33*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + gVu33*Conjugate[FR$deltaZ[{t, u}, {{}}, "R"]] + gAu11*FR$deltaZ[{u, t}, {{}}, "R"] + gVu11*FR$deltaZ[{u, t}, {{}}, "R"])*IndexDelta[e1x2, e2x2]}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc4 -> -GS,
     gc6 -> GS^2,
     gc16 -> GS,
     gc17 -> GS,
     gc18 -> GS,
     gc19 -> GS,
     gc20 -> GS,
     gc21 -> GS,
     gc22L -> -gAd33 + gVd33,
     gc22R -> gAd33 + gVd33,
     gc23L -> -gAu22 + gVu22,
     gc23R -> gAu22 + gVu22,
     gc24L -> -gAd11 + gVd11,
     gc24R -> gAd11 + gVd11,
     gc25L -> -gAd22 + gVd22,
     gc25R -> gAd22 + gVd22,
     gc26L -> -gAu33 + gVu33,
     gc26R -> gAu33 + gVu33,
     gc27L -> -gAu11 + gVu11,
     gc27R -> gAu11 + gVu11};

