ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Top-EFTfull-UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_88 = ', GC_88
