#############################################################################
#      written by the UFO converter
#############################################################################

MODEL = get_mass_width_fcts.o couplings.o lha_read.o printout.o rw_para.o model_functions.o couplings1.o couplings2.o couplings3.o couplings4.o mp_couplings1.o mp_couplings2.o mp_couplings3.o mp_couplings4.o