C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Gamma(3,2,1)) + Coup(2) * (Gamma(3,2,-1)*ProjM(-1,1) + Gamma(3,2,-1)*ProjP(-1,1))
C     
      SUBROUTINE FFV1_7P0_3(F1, F2, COUP1, COUP2, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 M3
      COMPLEX*16 P3(0:3)
      COMPLEX*16 V3(8)
      REAL*8 W3
      COMPLEX*16 DENOM
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      V3(3) = +F1(3)+F2(3)
      V3(4) = +F1(4)+F2(4)
      P3(0) = -V3(1)
      P3(1) = -V3(2)
      P3(2) = -V3(3)
      P3(3) = -V3(4)
      DENOM = 1D0/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI*
     $  W3))
      V3(5)= DENOM*(-CI)*(COUP1*(F1(5)*F2(7)+F1(6)*F2(8)+F1(7)*F2(5)
     $ +F1(8)*F2(6))+COUP2*(F1(5)*F2(7)+F1(6)*F2(8)+F1(7)*F2(5)+F1(8)
     $ *F2(6)))
      V3(6)= DENOM*(-CI)*(COUP1*(-F1(5)*F2(8)-F1(6)*F2(7)+F1(7)*F2(6)
     $ +F1(8)*F2(5))+COUP2*(-F1(5)*F2(8)-F1(6)*F2(7)+F1(7)*F2(6)+F1(8)
     $ *F2(5)))
      V3(7)= DENOM*(-CI)*(COUP1*(-CI*(F1(5)*F2(8)+F1(8)*F2(5))+CI
     $ *(F1(6)*F2(7)+F1(7)*F2(6)))+COUP2*(-CI*(F1(5)*F2(8)+F1(8)*F2(5))
     $ +CI*(F1(6)*F2(7)+F1(7)*F2(6))))
      V3(8)= DENOM*(-CI)*(COUP1*(-F1(5)*F2(7)-F1(8)*F2(6)+F1(6)*F2(8)
     $ +F1(7)*F2(5))+COUP2*(-F1(5)*F2(7)-F1(8)*F2(6)+F1(6)*F2(8)+F1(7)
     $ *F2(5)))
      END


