ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_yDM = ', MDL_YDM
      WRITE(*,*) 'mdl_lamHs = ', MDL_LAMHS
      WRITE(*,*) 'mdl_lamS = ', MDL_LAMS
      WRITE(*,*) 'mdl_mSDM = ', MDL_MSDM
      WRITE(*,*) 'mdl_mPsiT = ', MDL_MPSIT
      WRITE(*,*) 'mdl_mu = ', MDL_MU
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_lamHs__exp__3 = ', MDL_LAMHS__EXP__3
      WRITE(*,*) 'mdl_mSDM__exp__2 = ', MDL_MSDM__EXP__2
      WRITE(*,*) 'mdl_cH = ', MDL_CH
      WRITE(*,*) 'mdl_lamHs__exp__2 = ', MDL_LAMHS__EXP__2
      WRITE(*,*) 'mdl_cHBoxb = ', MDL_CHBOXB
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_mPsiT__exp__2 = ', MDL_MPSIT__EXP__2
      WRITE(*,*) 'mdl_mPsiT__exp__4 = ', MDL_MPSIT__EXP__4
      WRITE(*,*) 'mdl_mSDM__exp__4 = ', MDL_MSDM__EXP__4
      WRITE(*,*) 'mdl_mPsiT__exp__6 = ', MDL_MPSIT__EXP__6
      WRITE(*,*) 'mdl_mSDM__exp__6 = ', MDL_MSDM__EXP__6
      WRITE(*,*) 'mdl_yDM__exp__2 = ', MDL_YDM__EXP__2
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_ymt__exp__2 = ', MDL_YMT__EXP__2
      WRITE(*,*) 'mdl_ymt__exp__3 = ', MDL_YMT__EXP__3
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_g1__exp__4 = ', MDL_G1__EXP__4
      WRITE(*,*) 'mdl_cddc = ', MDL_CDDC
      WRITE(*,*) 'mdl_ced = ', MDL_CED
      WRITE(*,*) 'mdl_cee = ', MDL_CEE
      WRITE(*,*) 'mdl_ceua = ', MDL_CEUA
      WRITE(*,*) 'mdl_cHBoxa = ', MDL_CHBOXA
      WRITE(*,*) 'mdl_chd = ', MDL_CHD
      WRITE(*,*) 'mdl_chd__2 = ', MDL_CHD__2
      WRITE(*,*) 'mdl_cHe = ', MDL_CHE
      WRITE(*,*) 'mdl_cHl1 = ', MDL_CHL1
      WRITE(*,*) 'mdl_cHq1a = ', MDL_CHQ1A
      WRITE(*,*) 'mdl_cHua = ', MDL_CHUA
      WRITE(*,*) 'mdl_cld = ', MDL_CLD
      WRITE(*,*) 'mdl_cle = ', MDL_CLE
      WRITE(*,*) 'mdl_cll = ', MDL_CLL
      WRITE(*,*) 'mdl_clq1 = ', MDL_CLQ1
      WRITE(*,*) 'mdl_clua = ', MDL_CLUA
      WRITE(*,*) 'mdl_cqd1 = ', MDL_CQD1
      WRITE(*,*) 'mdl_cqe = ', MDL_CQE
      WRITE(*,*) 'mdl_cqq1b = ', MDL_CQQ1B
      WRITE(*,*) 'mdl_cqu1a = ', MDL_CQU1A
      WRITE(*,*) 'mdl_cud1a = ', MDL_CUD1A
      WRITE(*,*) 'mdl_cuub = ', MDL_CUUB
      WRITE(*,*) 'mdl_g1__exp__2 = ', MDL_G1__EXP__2
      WRITE(*,*) 'mdl_ceub = ', MDL_CEUB
      WRITE(*,*) 'mdl_cHq1b = ', MDL_CHQ1B
      WRITE(*,*) 'mdl_cHq3 = ', MDL_CHQ3
      WRITE(*,*) 'mdl_cHub = ', MDL_CHUB
      WRITE(*,*) 'mdl_club = ', MDL_CLUB
      WRITE(*,*) 'mdl_cqu1b = ', MDL_CQU1B
      WRITE(*,*) 'mdl_cuB = ', MDL_CUB
      WRITE(*,*) 'mdl_cud1b = ', MDL_CUD1B
      WRITE(*,*) 'mdl_cuHa = ', MDL_CUHA
      WRITE(*,*) 'mdl_vev__exp__3 = ', MDL_VEV__EXP__3
      WRITE(*,*) 'mdl_cuHb = ', MDL_CUHB
      WRITE(*,*) 'mdl_cuud = ', MDL_CUUD
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__4 = ', MDL_G__EXP__4
      WRITE(*,*) 'mdl_cdda = ', MDL_CDDA
      WRITE(*,*) 'mdl_cddb = ', MDL_CDDB
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
      WRITE(*,*) 'mdl_cG = ', MDL_CG
      WRITE(*,*) 'mdl_cqd8 = ', MDL_CQD8
      WRITE(*,*) 'mdl_cqq1a = ', MDL_CQQ1A
      WRITE(*,*) 'mdl_cqq1c = ', MDL_CQQ1C
      WRITE(*,*) 'mdl_cqq3 = ', MDL_CQQ3
      WRITE(*,*) 'mdl_cqu8a = ', MDL_CQU8A
      WRITE(*,*) 'mdl_cud8a = ', MDL_CUD8A
      WRITE(*,*) 'mdl_cuua = ', MDL_CUUA
      WRITE(*,*) 'mdl_cuuc = ', MDL_CUUC
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_cqu8b = ', MDL_CQU8B
      WRITE(*,*) 'mdl_cud8b = ', MDL_CUD8B
      WRITE(*,*) 'mdl_cuue = ', MDL_CUUE
      WRITE(*,*) 'mdl_cuuf = ', MDL_CUUF
      WRITE(*,*) 'mdl_cuG = ', MDL_CUG
