ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Top-EFTfull-UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_22 = ', GC_22
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_42 = ', GC_42
      WRITE(*,2) 'GC_53 = ', GC_53
      WRITE(*,2) 'GC_23 = ', GC_23
