C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(1,2)*P(2,2)) + Coup(2) * (P(-1,2)**2*Metric(1,2))
C     
      SUBROUTINE MP_VV1_3_0(V1, V2, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP1
      COMPLEX*32 COUP2
      COMPLEX*32 P2(0:3)
      COMPLEX*32 TMP11
      COMPLEX*32 TMP12
      COMPLEX*32 TMP4
      COMPLEX*32 TMP7
      COMPLEX*32 V1(*)
      COMPLEX*32 V2(*)
      COMPLEX*32 VERTEX
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      TMP11 = (V2(5)*P2(0)-V2(6)*P2(1)-V2(7)*P2(2)-V2(8)*P2(3))
      TMP12 = (P2(0)*P2(0)-P2(1)*P2(1)-P2(2)*P2(2)-P2(3)*P2(3))
      TMP4 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      TMP7 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      VERTEX = (-1Q0)*(+CI*(TMP7*TMP11*COUP1+TMP4*TMP12*COUP2))
      END


