C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(-1,1)*Gamma(-1,2,-2)*ProjP(-2,1)
C     
      SUBROUTINE FF5_0(F1, F2, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 P1(0:3)
      COMPLEX*16 TMP15
      COMPLEX*16 VERTEX
      P1(0) = F1(1)
      P1(1) = F1(2)
      P1(2) = F1(3)
      P1(3) = F1(4)
      TMP15 = (F1(7)*(F2(5)*(P1(0)-P1(3))-F2(6)*(P1(1)+CI*(P1(2))))
     $ +F1(8)*(F2(5)*(-P1(1)+CI*(P1(2)))+F2(6)*(P1(0)+P1(3))))
      VERTEX = COUP*(-CI * TMP15)
      END


