C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1) + ProjP(2,1)
C     
      SUBROUTINE MP_FF6_0(F1, F2, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      COMPLEX*32 F1(*)
      COMPLEX*32 F2(*)
      COMPLEX*32 TMP17
      COMPLEX*32 TMP18
      COMPLEX*32 VERTEX
      TMP17 = (F1(5)*F2(5)+F1(6)*F2(6))
      TMP18 = (F1(7)*F2(7)+F1(8)*F2(8))
      VERTEX = COUP*(-1Q0)*(+CI*(TMP17+TMP18))
      END


