C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(2,1)*Metric(1,3)
C     
      SUBROUTINE MP_VVV4_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      COMPLEX*32 P1(0:3)
      COMPLEX*32 TMP10
      COMPLEX*32 TMP11
      COMPLEX*32 V1(*)
      COMPLEX*32 V2(*)
      COMPLEX*32 V3(*)
      COMPLEX*32 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      TMP10 = (V3(5)*V1(5)-V3(6)*V1(6)-V3(7)*V1(7)-V3(8)*V1(8))
      TMP11 = (P1(0)*V2(5)-P1(1)*V2(6)-P1(2)*V2(7)-P1(3)*V2(8))
      VERTEX = COUP*(-CI * TMP10*TMP11)
      END


