C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,2)*Metric(1,2)
C     
      SUBROUTINE VVV2_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 P2(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP5
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      TMP1 = (P2(0)*V3(5)-P2(1)*V3(6)-P2(2)*V3(7)-P2(3)*V3(8))
      TMP5 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      VERTEX = COUP*(-CI * TMP1*TMP5)
      END


