C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1) + ProjP(2,1)
C     
      SUBROUTINE FF6_0(F1, F2, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 TMP11
      COMPLEX*16 TMP12
      COMPLEX*16 VERTEX
      TMP11 = (F2(5)*F1(5)+F2(6)*F1(6))
      TMP12 = (F2(7)*F1(7)+F2(8)*F1(8))
      VERTEX = COUP*(-1D0)*(+CI*(TMP11+TMP12))
      END


