C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (Gamma(3,2,1)) + Coup(2) * (Gamma(3,2,-1)*ProjM(-1,1) + Gamma(3,2,-1)*ProjP(-1,1))
C     
      SUBROUTINE MP_FFV1_4L1P0_3(P1, F2, COUP1, COUP2, M3, W3, P3,
     $  COEFF)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP2
      INCLUDE 'coef_specs.inc'
      COMPLEX*32 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      REAL*16 M3
      COMPLEX*32 F2(*)
      REAL*16 W3
      COMPLEX*32 P3(0:3)
      COMPLEX*32 P1(0:3)
      COMPLEX*32 COUP1
      P3(0) = +P1(0)+F2(1)
      P3(1) = +P1(1)+F2(2)
      P3(2) = +P1(2)+F2(3)
      P3(3) = +P1(3)+F2(4)
      COEFF(1,0,1)= -F2(7)*(+CI*(COUP2+COUP1))
      COEFF(2,0,1)= F2(8)*(+CI*(COUP2+COUP1))
      COEFF(3,0,1)= -F2(8)*(COUP2+COUP1)
      COEFF(4,0,1)= F2(7)*(+CI*(COUP2+COUP1))
      COEFF(1,0,2)= -F2(8)*(+CI*(COUP2+COUP1))
      COEFF(2,0,2)= F2(7)*(+CI*(COUP2+COUP1))
      COEFF(3,0,2)= F2(7)*(COUP2+COUP1)
      COEFF(4,0,2)= -F2(8)*(+CI*(COUP2+COUP1))
      COEFF(1,0,3)= -F2(5)*(+CI*(COUP2+COUP1))
      COEFF(2,0,3)= -F2(6)*(+CI*(COUP2+COUP1))
      COEFF(3,0,3)= F2(6)*(COUP2+COUP1)
      COEFF(4,0,3)= -F2(5)*(+CI*(COUP2+COUP1))
      COEFF(1,0,4)= -F2(6)*(+CI*(COUP2+COUP1))
      COEFF(2,0,4)= -F2(5)*(+CI*(COUP2+COUP1))
      COEFF(3,0,4)= -F2(5)*(COUP2+COUP1)
      COEFF(4,0,4)= F2(6)*(+CI*(COUP2+COUP1))
      END


