C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,4)*Metric(2,3)
C     
      SUBROUTINE MP_VVVV2P0_1(V2, V3, V4, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      REAL*16 M1
      COMPLEX*32 P1(0:3)
      COMPLEX*32 TMP7
      COMPLEX*32 V1(8)
      COMPLEX*32 V2(*)
      COMPLEX*32 V3(*)
      COMPLEX*32 V4(*)
      REAL*16 W1
      COMPLEX*32 DENOM
      V1(1) = +V2(1)+V3(1)+V4(1)
      V1(2) = +V2(2)+V3(2)+V4(2)
      V1(3) = +V2(3)+V3(3)+V4(3)
      V1(4) = +V2(4)+V3(4)+V4(4)
      P1(0) = -V1(1)
      P1(1) = -V1(2)
      P1(2) = -V1(3)
      P1(3) = -V1(4)
      TMP7 = (V2(5)*V3(5)-V2(6)*V3(6)-V2(7)*V3(7)-V2(8)*V3(8))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI
     $ * W1))
      V1(5)= DENOM*(-CI )* V4(5)*TMP7
      V1(6)= DENOM*(-CI )* V4(6)*TMP7
      V1(7)= DENOM*(-CI )* V4(7)*TMP7
      V1(8)= DENOM*(-CI )* V4(8)*TMP7
      END


