C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,2)*Metric(2,3)
C     
      SUBROUTINE MP_VVV7_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      COMPLEX*32 P2(0:3)
      COMPLEX*32 TMP6
      COMPLEX*32 TMP7
      COMPLEX*32 V1(*)
      COMPLEX*32 V2(*)
      COMPLEX*32 V3(*)
      COMPLEX*32 VERTEX
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      TMP6 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP7 = (V2(5)*V3(5)-V2(6)*V3(6)-V2(7)*V3(7)-V2(8)*V3(8))
      VERTEX = COUP*(-CI * TMP7*TMP6)
      END


