C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(3,1)*Metric(1,2) + P(2,3)*Metric(1,3) + P(1,2)*Metric(2,3)) + Coup(2) * (P(3,2)*Metric(1,2) + P(2,1)*Metric(1,3) + P(1,3)*Metric(2,3))
C     
      SUBROUTINE MP_VVV9_10_0(V1, V2, V3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP1
      COMPLEX*32 COUP2
      COMPLEX*32 P1(0:3)
      COMPLEX*32 P2(0:3)
      COMPLEX*32 P3(0:3)
      COMPLEX*32 TMP0
      COMPLEX*32 TMP1
      COMPLEX*32 TMP15
      COMPLEX*32 TMP16
      COMPLEX*32 TMP17
      COMPLEX*32 TMP18
      COMPLEX*32 TMP6
      COMPLEX*32 TMP7
      COMPLEX*32 TMP9
      COMPLEX*32 V1(*)
      COMPLEX*32 V2(*)
      COMPLEX*32 V3(*)
      COMPLEX*32 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      P3(0) = V3(1)
      P3(1) = V3(2)
      P3(2) = V3(3)
      P3(3) = V3(4)
      TMP0 = (V3(5)*P1(0)-V3(6)*P1(1)-V3(7)*P1(2)-V3(8)*P1(3))
      TMP1 = (V3(5)*P2(0)-V3(6)*P2(1)-V3(7)*P2(2)-V3(8)*P2(3))
      TMP15 = (V3(5)*V1(5)-V3(6)*V1(6)-V3(7)*V1(7)-V3(8)*V1(8))
      TMP16 = (V2(5)*P3(0)-V2(6)*P3(1)-V2(7)*P3(2)-V2(8)*P3(3))
      TMP17 = (V2(5)*P1(0)-V2(6)*P1(1)-V2(7)*P1(2)-V2(8)*P1(3))
      TMP18 = (P3(0)*V1(5)-P3(1)*V1(6)-P3(2)*V1(7)-P3(3)*V1(8))
      TMP6 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP7 = (V2(5)*V3(5)-V2(6)*V3(6)-V2(7)*V3(7)-V2(8)*V3(8))
      TMP9 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      VERTEX = (-1Q0)*(COUP1*(+CI*(TMP0*TMP9+TMP15*TMP16+TMP6*TMP7))
     $ +COUP2*(+CI*(TMP1*TMP9+TMP15*TMP17+TMP7*TMP18)))
      END


