C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(3,1)*Metric(1,2)) + Coup(2) * (P(3,2)*Metric(1,2)) + Coup(3) * (P(3,3)*Metric(1,2)) + Coup(4) * (P(2,1)*Metric(1,3)) + Coup(5) * (P(2,2)*Metric(1,3)) + Coup(6) * (P(2,3)*Metric(1,3)) + Coup(7) * (P(1,2)*Metric(2,3)) + Coup(8) * (P(1,3)*Metric(2,3))
C     
      SUBROUTINE VVV1_2_3_4_5_6_7_8_0(V1, V2, V3, COUP1, COUP2, COUP3,
     $  COUP4, COUP5, COUP6, COUP7, COUP8,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 COUP7
      COMPLEX*16 COUP8
      COMPLEX*16 P1(0:3)
      COMPLEX*16 P2(0:3)
      COMPLEX*16 P3(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 TMP15
      COMPLEX*16 TMP16
      COMPLEX*16 TMP17
      COMPLEX*16 TMP18
      COMPLEX*16 TMP3
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP7
      COMPLEX*16 TMP9
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      P3(0) = V3(1)
      P3(1) = V3(2)
      P3(2) = V3(3)
      P3(3) = V3(4)
      TMP0 = (V3(5)*P1(0)-V3(6)*P1(1)-V3(7)*P1(2)-V3(8)*P1(3))
      TMP1 = (V3(5)*P2(0)-V3(6)*P2(1)-V3(7)*P2(2)-V3(8)*P2(3))
      TMP15 = (V3(5)*V1(5)-V3(6)*V1(6)-V3(7)*V1(7)-V3(8)*V1(8))
      TMP16 = (V2(5)*P3(0)-V2(6)*P3(1)-V2(7)*P3(2)-V2(8)*P3(3))
      TMP17 = (V2(5)*P1(0)-V2(6)*P1(1)-V2(7)*P1(2)-V2(8)*P1(3))
      TMP18 = (P3(0)*V1(5)-P3(1)*V1(6)-P3(2)*V1(7)-P3(3)*V1(8))
      TMP3 = (V3(5)*P3(0)-V3(6)*P3(1)-V3(7)*P3(2)-V3(8)*P3(3))
      TMP5 = (V2(5)*P2(0)-V2(6)*P2(1)-V2(7)*P2(2)-V2(8)*P2(3))
      TMP6 = (P2(0)*V1(5)-P2(1)*V1(6)-P2(2)*V1(7)-P2(3)*V1(8))
      TMP7 = (V2(5)*V3(5)-V2(6)*V3(6)-V2(7)*V3(7)-V2(8)*V3(8))
      TMP9 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      VERTEX = (-1D0)*(TMP15*(+CI*(TMP17*COUP4+TMP5*COUP5+TMP16*COUP6))
     $ +(TMP9*(+CI*(TMP0*COUP1+TMP1*COUP2+TMP3*COUP3))+TMP7*(+CI*(TMP6
     $ *COUP7+TMP18*COUP8))))
      END


