C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
Coup(1) * (P(3,2)*Metric(1,2) + P(2,1)*Metric(1,3) + P(1,3)*Metric(2,3)) + Coup(2) * (P(3,1)*Metric(1,2) + P(2,3)*Metric(1,3) + P(1,2)*Metric(2,3))
C     
      SUBROUTINE VVV10_9P0_1(V2, V3, COUP1, COUP2, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      REAL*8 M1
      COMPLEX*16 P1(0:3)
      COMPLEX*16 P2(0:3)
      COMPLEX*16 P3(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 TMP16
      COMPLEX*16 TMP17
      COMPLEX*16 TMP7
      COMPLEX*16 V1(8)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      REAL*8 W1
      COMPLEX*16 DENOM
      P2(0) = V2(1)
      P2(1) = V2(2)
      P2(2) = V2(3)
      P2(3) = V2(4)
      P3(0) = V3(1)
      P3(1) = V3(2)
      P3(2) = V3(3)
      P3(3) = V3(4)
      V1(1) = +V2(1)+V3(1)
      V1(2) = +V2(2)+V3(2)
      V1(3) = +V2(3)+V3(3)
      V1(4) = +V2(4)+V3(4)
      P1(0) = -V1(1)
      P1(1) = -V1(2)
      P1(2) = -V1(3)
      P1(3) = -V1(4)
      TMP0 = (V3(5)*P1(0)-V3(6)*P1(1)-V3(7)*P1(2)-V3(8)*P1(3))
      TMP1 = (V3(5)*P2(0)-V3(6)*P2(1)-V3(7)*P2(2)-V3(8)*P2(3))
      TMP16 = (V2(5)*P3(0)-V2(6)*P3(1)-V2(7)*P3(2)-V2(8)*P3(3))
      TMP17 = (V2(5)*P1(0)-V2(6)*P1(1)-V2(7)*P1(2)-V2(8)*P1(3))
      TMP7 = (V2(5)*V3(5)-V2(6)*V3(6)-V2(7)*V3(7)-V2(8)*V3(8))
      DENOM = 1D0/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 -CI*
     $  W1))
      V1(5)= DENOM*(-1D0)*(COUP1*(+CI*(V2(5)*TMP1+V3(5)*TMP17+P3(0)
     $ *TMP7))+COUP2*(+CI*(V2(5)*TMP0+V3(5)*TMP16+P2(0)*TMP7)))
      V1(6)= DENOM*(-1D0)*(COUP1*(+CI*(V2(6)*TMP1+V3(6)*TMP17+P3(1)
     $ *TMP7))+COUP2*(+CI*(V2(6)*TMP0+V3(6)*TMP16+P2(1)*TMP7)))
      V1(7)= DENOM*(-1D0)*(COUP1*(+CI*(V2(7)*TMP1+V3(7)*TMP17+P3(2)
     $ *TMP7))+COUP2*(+CI*(V2(7)*TMP0+V3(7)*TMP16+P2(2)*TMP7)))
      V1(8)= DENOM*(-1D0)*(COUP1*(+CI*(V2(8)*TMP1+V3(8)*TMP17+P3(3)
     $ *TMP7))+COUP2*(+CI*(V2(8)*TMP0+V3(8)*TMP16+P2(3)*TMP7)))
      END


