C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVV8_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 P3(0:3)
      COMPLEX*16 TMP18
      COMPLEX*16 TMP7
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      P3(0) = V3(1)
      P3(1) = V3(2)
      P3(2) = V3(3)
      P3(3) = V3(4)
      TMP18 = (P3(0)*V1(5)-P3(1)*V1(6)-P3(2)*V1(7)-P3(3)*V1(8))
      TMP7 = (V2(5)*V3(5)-V2(6)*V3(6)-V2(7)*V3(7)-V2(8)*V3(8))
      VERTEX = COUP*(-CI * TMP7*TMP18)
      END


