#!/usr/bin/env python3

# Extracts information from MadGraph output to create a SLHA file with cross-section blocks
# 1) Run getSLHA to extract the information of the MadGraph output
# and generate a SLHA file containing the cross-sections

import sys, os
import logging
from collections import OrderedDict
import gzip
import fnmatch

# Configure basic logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')
logger = logging.getLogger()

def getSLHAFile(inputLHE, output_dir=None, pidList=[-5000006, 5000006], mg5_path='/home/vrocca/MadGraph/MG5_aMC_v3_6_3/'):
    """
    Uses the LHE file generated by MadGraph
    to generate an SLHA file which includes the XSECTION blocks.
    
    :param inputLHE: Path to the MadGraph LHE file.  
    :param output_dir: Directory to save the SLHA output. Will use masses to name it VLF_m1_m2.slha.  
    :param pidList: List of final states PIDs for the process (assumes a single process),
                 used for defining the xsection block. If not given, will try to read it from
                 the process card.
                 
    
    :return: Path to the slha file or False if failed
    """
    
    #Use MadGraph banner reader:
    madgraphPath = os.path.abspath(mg5_path)
    if madgraphPath not in sys.path:
        sys.path.append(madgraphPath)
        
    try:
        from madgraph.various.banner import Banner
    except ImportError:
        logger.error(f"Could not import Banner from {madgraphPath}. Check your MG5 path.")
        return False
        
    lheFile = inputLHE   
    if not os.path.isfile(lheFile):
        logger.error("File %s not found" % lheFile)
        return False
    
    try:
        if lheFile.endswith('.gz'):
            f = gzip.open(lheFile, 'rt')
        else: 
            f = open(lheFile, 'r')
            
        banner = Banner()
        banner.read_banner(f)
        f.close()
    except Exception as e:
        logger.error(f"Error reading {lheFile}: {e}")
        return False

    #Check if input file is MG5 banner or SLHA file
    if not 'init' in banner or not 'slha' in banner:
        logger.error("Input file %s does not contain required data" % lheFile)
        return False
       
    # Collect necessary info:
    slhaData = banner['slha'] 

    # --- EXTRACT MASSES FOR FILE NAMING ---
    m1, m2 = 0.0, 0.0
    in_mass_block = False
    for line in slhaData.split('\n'):
        clean_line = line.strip().lower()
        if clean_line.startswith('block mass'):
            in_mass_block = True
            continue
        if clean_line.startswith('block ') and in_mass_block:
            in_mass_block = False
        
        if in_mass_block and clean_line and not clean_line.startswith('#'):
            parts = clean_line.split()
            if len(parts) >= 2:
                try:
                    pdg = int(parts[0])
                    if pdg == 5000006:
                        m1 = float(parts[1])
                    elif pdg == 5000022:
                        m2 = float(parts[1])
                except ValueError:
                    pass
    
    if output_dir is not None:
        m1_str = str(int(m1)) if m1.is_integer() else str(m1)
        m2_str = str(int(m2)) if m2.is_integer() else str(m2)
        out_filename = f"VLF_{m1_str}_{m2_str}.slha"
        slhaFile = os.path.join(output_dir, out_filename)
        # Create output dirs if they do not exist
        os.makedirs(output_dir, exist_ok=True)
    else:
        slhaFile = inputLHE[:inputLHE.rfind('.lhe')] + '.slha'
        
    logger.debug('Creating SLHA file %s' % slhaFile)

    if pidList is None or not pidList:
        # Use QNUMBERS blocks to get particle label -> PDG dict:
        slhaLines = slhaData.split('\n')  
        qnumbers = [l for l in slhaLines if 'block qnumbers' in l.lower()]
        particleLabels = {x.split('#')[1].strip() : eval(x.split('#')[0].split()[-1]) for x in qnumbers}
        
        # Try to guess anti-particle labels:
        for label, pdg in list(particleLabels.items()):
            if -pdg in particleLabels.values():
                continue
            else:
                particleLabels[label+'~'] = -pdg    

        #Get generated processes:
        finalStatesDict = {}
        iproc = 0
        for l in banner['mg5proccard'].split('\n'):
            if not l or l[0] == '#':
                continue
            l = l.strip()
            if l[:8] == 'generate':
                l = l[l.find('generate')+8:]
            elif l[:11] == 'add process':
                l = l[l.find('add process')+11:]
            else:
                continue

            l = l[:l.find('[')]
            l = l.strip()        
            
            #Get final states and process ID
            finalStates = l.split('>')[1]
            finalStates = finalStates.split(',')[0]
            finalStates = finalStates.strip().split()
            finalStates = [particleLabels[f] if f in particleLabels else f for f in finalStates[:]]

            #Store the process ID with its final states:
            if not iproc in finalStatesDict:        
                finalStatesDict[iproc] = finalStates
            else:
                logger.error("Error reading processes. Process ID %i appears more than once." % iproc)
                return False
            iproc += 1
    else:
        # Evaluate PIDs from string if they came from argparse, or keep them if they are ints
        pidList_eval = [int(p) for p in pidList]
        finalStatesDict = {1 : sorted(pidList_eval)}

    #Get total cross-section,number of events
    xsecTotal = banner.get_cross()
    if xsecTotal <= 0.:
        logger.error("Total cross-section is zero?")
        return False
    
    #Get sqrts and cross-section for each process:
    info = banner['init'].split('\n')[0].split()
    sqrts = eval(info[2]) + eval(info[3])
    pdgInitial = list(banner.get_pdg_beam())
    processXsecs = {}
    
    for l in banner['init'].split('\n')[1:]:
        if not l.strip() or l.strip()[0] == '<':
            continue
        vals = [eval(x) for x in l.split()]
        xsec, xsecErr, _, procID = vals
        if not procID in finalStatesDict:
            logger.error("Process ID %i not found in LHE file" % procID)
            return False
        if not procID in processXsecs:
            processXsecs[procID] = {'xsec (pb)' : xsec, 'xsecErr (pb)' : xsecErr}
        else:
            logger.error("Error reading subprocess cross-sections. The process ID = %i appears multiple times" % procID)
            return False

    #Check:
    if abs(xsecTotal - sum([x['xsec (pb)'] for x in processXsecs.values()]))/xsecTotal > 0.001:
        logger.error("Total cross-section does not agree with sum of subprocesses")
        return False 
    
    #Write SLHA file:
    slhaF = open(slhaFile,'w')
    slhaF.write(slhaData)
    slhaF.write('\n\n')
    processXsecs = OrderedDict(sorted(processXsecs.items(), 
                                      key=lambda proc: proc[1]['xsec (pb)'], reverse=True))
    
    # --- CORRECTED LOOP FOR WRITING CROSS SECTIONS ---
    for procID in processXsecs:
        finalStates = finalStatesDict[procID]
        xsec = processXsecs[procID]['xsec (pb)']
        xsecErr = processXsecs[procID]['xsecErr (pb)']
        comment = "# xsec unit: pb xsec error: %1.3e" % (xsecErr)
        
        xsecLine = "\nXSECTION %1.3e " % (sqrts)
        xsecLine += " ".join([str(pdg) for pdg in pdgInitial])
        xsecLine += " %i " % len(finalStates)
        xsecLine += " ".join([str(pdg) for pdg in finalStates])
        
        slhaF.write(xsecLine+' '+comment+' \n')        
        slhaF.write("  0  0  0  0  0  0  %1.4e ufo2slha 1.0\n" % xsec)    
        
    slhaF.close()
    
    logger.info("Finished SLHA creation for %s" % slhaFile)
    return slhaFile

# --- SEPARATED PROCESS DIRECTORY FUNCTION ---
def process_directory(base_dir, pattern, pid_list, mg5_path, output_dir):
    """
    Recursively searches for files matching the pattern in base_dir
    and runs getSLHAFile on each of them.
    """
    processed_count = 0
    failed_count = 0
    
    logger.info(f"Searching for '{pattern}' in directory: {base_dir}")
    logger.info(f"Output directory set to: {output_dir}")
    
    for root, dirs, files in os.walk(base_dir):
        for filename in fnmatch.filter(files, pattern):
            lhe_path = os.path.join(root, filename)
            logger.info(f"Processing found file: {lhe_path}")
            
            # Execute the procedure
            result = getSLHAFile(lhe_path, output_dir=output_dir, pidList=pid_list, mg5_path=mg5_path)
            
            if result:
                processed_count += 1
            else:
                failed_count += 1
                
    logger.info("==================================================")
    logger.info(f"Batch Processing Complete.")
    logger.info(f"Successfully created SLHA files: {processed_count}")
    logger.info(f"Failed files: {failed_count}")
    logger.info("==================================================")


if __name__ == "__main__":
    import argparse    
    ap = argparse.ArgumentParser(description=
            "Read LHE event files generated by MG5 in a batch and convert them to SLHA files with cross-section blocks." )
    
    # Changed input to accept a directory instead of a single file
    ap.add_argument('-d', '--dir', required=True,
            help='Path to the base directory (e.g. your Events folder) containing the LHE files.')
            
    # Added output directory argument
    ap.add_argument('-o', '--outdir', required=True,
            help='Path to the directory where all SLHA files will be saved.')
    
    # Added argument for pattern matching
    ap.add_argument('-pt', '--pattern', default='*events.lhe*',
            help='Pattern to match the LHE files. Default is "*events.lhe*" (matches .lhe and .lhe.gz).')
            
    ap.add_argument('-pids', '--pids',
            help='list of final state PIDs (e.g. -1000011 1000011). If not given, will try to guess from process card.',
            default=[-5000006, 5000006], nargs='+')
            
    ap.add_argument('--mg5', default='/home/vrocca/MadGraph/MG5_aMC_v3_6_3/',
            help='Path to the MadGraph 5 installation directory.')
    
    args = ap.parse_args()
    
    # Ensure directory exists
    if not os.path.isdir(args.dir):
        logger.error(f"The provided path '{args.dir}' is not a valid directory.")
        sys.exit(1)
        
    # Ensure output directory exists (creates it if it doesn't)
    os.makedirs(args.outdir, exist_ok=True)
        
    process_directory(args.dir, args.pattern, args.pids, args.mg5, args.outdir)