C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjP(2,1)
C     
      SUBROUTINE FFS3L2_3(P2, F1, COUP, M3, W3, P3, COEFF)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      REAL*8 M3
      COMPLEX*16 P3(0:3)
      COMPLEX*16 P2(0:3)
      REAL*8 W3
      COMPLEX*16 COUP
      INCLUDE 'coef_specs.inc'
      COMPLEX*16 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*16 F1(*)
      P3(0) = +F1(1)+P2(0)
      P3(1) = +F1(2)+P2(1)
      P3(2) = +F1(3)+P2(2)
      P3(3) = +F1(4)+P2(3)
      COEFF(1,0,1)= 0D0
      COEFF(1,0,2)= 0D0
      COEFF(1,0,3)= COUP*CI * F1(7)
      COEFF(1,0,4)= COUP*CI * F1(8)
      END


