C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)
C     
      SUBROUTINE MP_FFS1L3_1(P3, F2, COUP, M1, W1, P1, COEFF)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 F2(*)
      COMPLEX*32 P3(0:3)
      REAL*16 M1
      REAL*16 W1
      COMPLEX*32 COUP
      INCLUDE 'coef_specs.inc'
      COMPLEX*32 COEFF(MAXLWFSIZE,0:VERTEXMAXCOEFS-1,MAXLWFSIZE)
      COMPLEX*32 P1(0:3)
      P1(0) = +F2(1)+P3(0)
      P1(1) = +F2(2)+P3(1)
      P1(2) = +F2(3)+P3(2)
      P1(3) = +F2(4)+P3(3)
      COEFF(1,0,1)= COUP*CI * F2(5)*M1
      COEFF(2,0,1)= COUP*CI * F2(6)*M1
      COEFF(3,0,1)= COUP*(-1Q0)*(F2(5)*(-CI*(P1(0))+CI*(P1(3)))+F2(6)
     $ *(+CI*(P1(1))-P1(2)))
      COEFF(4,0,1)= COUP*(F2(5)*(-1Q0)*(+CI*(P1(1))+P1(2))+F2(6)*(+CI
     $ *(P1(0)+P1(3))))
      COEFF(1,1,1)= 0Q0
      COEFF(2,1,1)= 0Q0
      COEFF(3,1,1)= COUP*CI * F2(5)
      COEFF(4,1,1)= COUP*CI * F2(6)
      COEFF(1,2,1)= 0Q0
      COEFF(2,2,1)= 0Q0
      COEFF(3,2,1)= COUP*-CI * F2(6)
      COEFF(4,2,1)= COUP*-CI * F2(5)
      COEFF(1,3,1)= 0Q0
      COEFF(2,3,1)= 0Q0
      COEFF(3,3,1)= COUP*F2(6)
      COEFF(4,3,1)= COUP*-F2(5)
      COEFF(1,4,1)= 0Q0
      COEFF(2,4,1)= 0Q0
      COEFF(3,4,1)= COUP*-CI * F2(5)
      COEFF(4,4,1)= COUP*CI * F2(6)
      END


