C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,3)*Metric(1,2) + P(2,1)*Metric(1,3)
C     
      SUBROUTINE VVV13_0(V1, V2, V3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 P1(0:3)
      COMPLEX*16 P3(0:3)
      COMPLEX*16 TMP10
      COMPLEX*16 TMP11
      COMPLEX*16 TMP3
      COMPLEX*16 TMP5
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      COMPLEX*16 VERTEX
      P1(0) = V1(1)
      P1(1) = V1(2)
      P1(2) = V1(3)
      P1(3) = V1(4)
      P3(0) = V3(1)
      P3(1) = V3(2)
      P3(2) = V3(3)
      P3(3) = V3(4)
      TMP10 = (V3(5)*V1(5)-V3(6)*V1(6)-V3(7)*V1(7)-V3(8)*V1(8))
      TMP11 = (P1(0)*V2(5)-P1(1)*V2(6)-P1(2)*V2(7)-P1(3)*V2(8))
      TMP3 = (V3(5)*P3(0)-V3(6)*P3(1)-V3(7)*P3(2)-V3(8)*P3(3))
      TMP5 = (V2(5)*V1(5)-V2(6)*V1(6)-V2(7)*V1(7)-V2(8)*V1(8))
      VERTEX = COUP*(-1D0)*(+CI*(TMP3*TMP5+TMP10*TMP11))
      END


